FROM mysql/mysql-server:5.7


RUN yum install -y oracle-nodejs-release-el7 oracle-release-el7
RUN yum install nodejs -y

RUN npm install multer
RUN npm install morgan
RUN npm install debug
RUN npm install ect
RUN npm install express
RUN npm install body-parser
RUN npm install md5
RUN npm install request
COPY _entrypoint.sh /var/_entrypoint.sh
 
# CMD ["mysqld"]
# ENTRYPOINT mysqld
# ENTRYPOINT sh /var/_entrypoint.sh
RUN mysqld
# CMD ["sh", "/var/_entrypoint.sh"]
